members/urls.py
from django.urls import path
from . import views



app_name = 'members'

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.people, name='people'),
]

project/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls', namespace='members')),
    path('', views.home, name='home'),

]

members/models.py
from django.db import models

# Create your models here.

from django.db import models

class Member(models.Model):
  firstname = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  phone = models.IntegerField()
  joined_date = models.DateField()

members/views.py


# Create your views here.
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

def people(request):
    return render(request,'people.html')

project/views.py
# project/views.py

from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

templates/index.html
<!-- members/templates/members/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>Welcome to the Home Page</h1>
    <p>This is a simple template for the root URL.</p>
    <a href="{% url 'members:people' %}">Go to people Page</a>
</body>
</html>

templates/people.html
<!-- members/templates/members/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
   <h2> hii </h2>
</body>
</html>